version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - argparse
  - commitizen
  - geoips
  - kwargs
  - mypy
  - NOAA
  - pinkrst
  - pytest
  - Uttmark
ignoreWords:
  - outdirs
  - retval
  - addopts
  - repr
  - runcmd
  - sphinxcontrib
  - testpaths
  - xdist
import: []
