version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - argparse
  - CIRA
  - commitizen
  - dateparser
  - geoips
  - IODC
  - isort
  - kwargs
  - mccabe
  - meteosat
  - mypy
  - NOAA
  - norecursedirs
  - numpy
  - pathlib
  - pinkrst
  - pycodestyle
  - pydantic
  - pydocstyle
  - Pyflakes
  - Pylint
  - pytest
  - pythonpath
  - pyupgrade
  - pyyaml
  - rabbitmq
  - seviri
  - tryceratops
  - typer
  - Uttmark
  - xarray
ignoreWords:
  - outdirs
  - retval
  - addopts
  - repr
  - runcmd
  - sphinxcontrib
  - testpaths
  - xdist
import: []
