[pytest]
# Currently importlib required for CLI, but breaks pytest-based integration tests
# addopts = -v -rf --ff --cov-report=term-missing -m "not integration" --import-mode=importlib
addopts = -v -rf --ff --cov-report=term-missing -m "not limited_test_dataset_availability"
pythonpath = .
testpaths = tests
norecursedirs = xarray_utils
markers =
    # 'integration', 'spans_multiple_packages', and 'limited_test_dataset_availability'
    # markers can be applied concurrently with any other marker.

    # All other markers should be disjoint - there should be NO common tests between
    # them.
    # Individual repo markers:
    #    base, full
    # GeoIPS System Implementation markers:
    #    realtime, external_preprocessing, scheduler, database, scrubber, downloader

    ###################################################################################
    ###################################################################################
    # integration, spans_multiple_packages, and limited_test_dataset_availability
    # can all be applied concurrently with other markers.

    integration: CONCURRENT - marks tests as integration (select with '-m "integration"')
    spans_multiple_packages: CONCURRENT - marks integration tests that test functionality that could fail due to errors in multiple repositories. e.g. listing or validating all plugins, etc. Allows calling tests to ensure the same error will not cause tests in multiple repos to fail.
    limited_test_dataset_availability: CONCURRENT - marks integration tests that may have limited test dataset availability so may not be available to all users.

    ###################################################################################
    ###################################################################################
    # base+full is a complete test of everything within the current repository
    # If any tests require functionality in another plugin repository (besides the
    # geoips repository), they should additionally be marked with
    # "spans_multiple_packages"

    # These markers should be disjoint - there should be
    # NO common tests between them.

    base: OPTIONAL INDEPENDENT - integration tests that complete very quickly and require only a minimal installation for testing basic functionality within the current repository
    full: REQUIRED INDEPENDENT - integration tests that require a 'full' installation for testing all functionality within the current repository. 'full' marker includes all tests for the current repo except for tests included in the optional 'base' marker.