apiVersion: geoips/driver/v1
kind: Service
name: example-for-spec
docstring: |
description: This is an example GeoIPS-nRTP service specification.
spec:
  service_namespace: example_service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin_test
  run:
    - file_watching_service:
        kind: data_monitor
        name: file_system_polling # this is the plugin name
        config:
          path: /path/to/watch
    - this_builds_jobs:
        kind: job_builder
        name: dummy_job_builder
        config: null # just using defaults
    - dispatch_those_jobs:
        kind: dispatcher
        name: serial
        config:
          workflow: # this could also be a file path
            apiVersion: geoips/v1
            interface: workflows
            family: order_based
            name: read_test_v1
            docstring: |
              11.2 µm Infrared.

              This product utilizes channel 14 (11.2 µm) and
              highlights areas of deep convection within a Tropical Cyclone.
            description: 11.2 µm Infrared.
            spec:
              steps:
                reader:
                  kind: reader
                  name: abi_netcdf
                  arguments:
                    variables: ['B14BT']
                algorithm:
                  kind: algorithm
                  name: single_channel
                  arguments:
                    variables: ['B14BT']
                    output_data_range: [-90.0, 30.0]
                    input_units: Kelvin
                    output_units: celsius
                    min_outbounds: crop
                    max_outbounds: crop
                    norm: null
                    inverse: null
