service:
  name: "querier-service"
  check_interval: 5
  
file_requirements:
  cwc_processing:
    required_files: ["cwc", "clavrx"]
    template: "add_cloud_water_content"
    
rabbitmq:
  queues:
    file_notifications:
      consume: true
    job_submissions:
      publish: true
    job_status:
      consume: true
      
logging:
  level: "INFO"
