service:
  name: "watcher-service"
  watch_directory: "/data/input"
  
patterns:
  cwc: "clavrx_OR_ABI-L1b-RadF-M6C01_G16_s*.CWC.h5"
  clavrx: "clavrx_OR_ABI-L1b-RadF-M6C01_G16_s*.level2.hdf"

rabbitmq:
  queues:
    file_notifications: 
      durable: true
      
logging:
  level: "INFO"
