"""CLI ``courier plugins`` sub-app — list plugins."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Annotated

import typer
from lexeme_type.lexeme import Lexeme
from rich import box
from rich.console import Console
from rich.table import Table

from courier.cli.feedback import load_config_or_exit
from courier.interfaces import (
    data_monitor_configs,
    data_monitors,
    dispatchers,
    job_builders,
)

if TYPE_CHECKING:
    from collections.abc import Iterator

    from courier.interfaces.discovery import (
        ClassPluginRegistry,
        ConfigPluginRegistry,
    )
    from courier.schema.v1alpha1.service_config import ServiceConfigModel

#: Shown when no service config supplies one. This used to display the
#: plugin-registry namespace, which named an implementation detail rather
#: than anything an operator had set.
DEFAULT_NAMESPACE = "courier"

plugins_app = typer.Typer(
    name="plugins",
    help="Inspect courier's plugins.",
    no_args_is_help=True,
)

# Positional and optional: with no config every installed plugin is listed;
# with one, only the plugins that config actually references.
_CONFIG_ARGUMENT = typer.Argument(
    metavar="[CONFIG]",
    help="Service YAML to filter by. Omit to list every installed plugin.",
)
_NAMESPACE_OPTION = typer.Option(
    "--namespace",
    "-n",
    help="Override the namespace read from the YAML metadata.",
)
_JSON_OPTION = typer.Option(
    "--json",
    "-j",
    help="Emit machine-readable JSON to stdout instead of a table.",
)

#: Every registry courier can list. Only the three plugin interfaces are
#: runnable pipeline steps -- see :data:`RUN_KINDS`.
PLUGIN_REGISTRIES: dict[str, ClassPluginRegistry | ConfigPluginRegistry] = {
    "data_monitor_configs": data_monitor_configs,
    "data_monitors": data_monitors,
    "dispatchers": dispatchers,
    "job_builders": job_builders,
}

#: Interfaces that can appear as a ``spec.run`` step. ``data_monitor_configs``
#: is data referenced by a monitor's ``metadata-tools``, never a step of its own.
RUN_KINDS: frozenset[str] = frozenset(
    {"data_monitors", "job_builders", "dispatchers"},
)

# Mapping from YAML ``kind`` values (singular, as generated by ``courier init``
# and used in existing configs) to the canonical :data:`PLUGIN_REGISTRIES` keys
# (plural, matching the ``courier.interfaces`` module names).
# Keys are :class:`~lexeme_type.lexeme.Lexeme` so lookup is case- and
# whitespace-insensitive, matching the comparison in
# :func:`_config_references_plugin`.
_KIND_TO_REGISTRY_KEY: dict[Lexeme, str] = {
    Lexeme("data_monitor"): "data_monitors",
    Lexeme("job_builder"): "job_builders",
    Lexeme("dispatcher"): "dispatchers",
}


def normalize_kind(kind: str) -> str:
    """Normalize a YAML ``kind`` value to its :data:`PLUGIN_REGISTRIES` key.

    Configs written by ``courier init`` use singular kind strings
    (``"data_monitor"``, ``"job_builder"``, ``"dispatcher"``); the
    internal registries are keyed by the plural interface names.  This
    function maps between the two conventions so downstream code can
    compare against or look up from :data:`PLUGIN_REGISTRIES` without
    hard-coding the convention.

    The lookup uses :class:`~lexeme_type.lexeme.Lexeme` so that
    incidental whitespace or case variation in YAML ``kind`` values
    does not cause silent plugin skipping.
    """
    return _KIND_TO_REGISTRY_KEY.get(Lexeme(kind), kind)


# Distinct color per plugin type for at-a-glance scanning.
_TYPE_STYLES: dict[str, str] = {
    "data_monitor_configs": "cyan",
    "data_monitors": "magenta",
    "dispatchers": "green",
    "job_builders": "yellow",
}


def _discover_plugins() -> Iterator[tuple[str, str]]:
    """Discover all plugins by querying each interface's registry."""
    for kind, registry in PLUGIN_REGISTRIES.items():
        for name in registry.names():
            yield kind, name


def _config_references_plugin(
    config: ServiceConfigModel,
    plugin_type: str,
    plugin_name: str,
) -> bool:
    """Return True if the config references the plugin."""
    for section in config.spec.run:
        if (
            normalize_kind(section.spec.kind) == plugin_type
            and Lexeme(section.spec.name) == plugin_name
        ):
            return True
    return False


def get_plugins(
    config_file: Path | ServiceConfigModel | None,
    namespace: str | None,
) -> tuple[str, list[list[str]]]:
    """Return ``(namespace, [[plugin_type, plugin_name], ...])``."""
    if not isinstance(config_file, Path):
        config = config_file
    else:
        config = load_config_or_exit(config_file)
    if config:
        namespace = (
            config.metadata.namespace if config.metadata.namespace else namespace
        )
    ns = namespace or DEFAULT_NAMESPACE
    plugins: list[list[str]] = []
    for plugin_type, registry in PLUGIN_REGISTRIES.items():
        for plugin_name in registry.names():
            if not config or _config_references_plugin(
                config,
                plugin_type,
                plugin_name,
            ):
                plugins.append([plugin_type, plugin_name])
    return ns, plugins


def _render_plugins_table(
    namespace: str,
    plugins: list[list[str]],
    config_file: Path | None,
) -> None:
    """Render plugins as a rich table, grouped by plugin type."""
    console = Console()

    if config_file is not None:
        caption = f"Filtered by config: [italic]{config_file}[/italic]"
    else:
        caption = f"[dim]{len(plugins)} plugin(s) discovered[/dim]"

    table = Table(
        title=f"Courier plugins  ·  namespace: [bold]{namespace}[/bold]",
        caption=caption,
        box=box.ROUNDED,
        header_style="bold white on blue",
        show_lines=False,
        expand=False,
    )
    table.add_column("Plugin type", style="bold", no_wrap=True)
    table.add_column("Name", overflow="fold")

    if not plugins:
        table.add_row("[dim]—[/dim]", "[dim italic]no plugins found[/dim italic]")
        console.print(table)
        return

    grouped: dict[str, list[str]] = {}
    for plugin_type, plugin_name in plugins:
        grouped.setdefault(plugin_type, []).append(plugin_name)

    last_type = list(grouped.keys())[-1]
    for plugin_type, names in grouped.items():
        style = _TYPE_STYLES.get(plugin_type, "white")
        for i, name in enumerate(sorted(names)):
            type_cell = f"[{style}]{plugin_type}[/{style}]" if i == 0 else ""
            table.add_row(type_cell, name)
        if plugin_type != last_type:
            table.add_section()

    console.print(table)


def _render_plugins_json(namespace: str, plugins: list[list[str]]) -> None:
    """Emit plugins as JSON on stdout (clean, pipeable, no styling)."""
    payload = {
        "namespace": namespace,
        "plugins": [
            {"type": plugin_type, "name": plugin_name}
            for plugin_type, plugin_name in plugins
        ],
    }
    # Plain print so output is clean for piping into jq, files, etc.
    typer.echo(json.dumps(payload, indent=2))


@plugins_app.command("list")
def list_cmd(
    config: Annotated[Path | None, _CONFIG_ARGUMENT] = None,
    namespace: Annotated[str | None, _NAMESPACE_OPTION] = None,
    json_output: Annotated[bool, _JSON_OPTION] = False,
) -> None:
    """Print every plugin the service is expected to use."""
    loaded = load_config_or_exit(config) if config else None
    ns, plugins = get_plugins(loaded, namespace)
    if json_output:
        _render_plugins_json(ns, plugins)
    else:
        _render_plugins_table(ns, plugins, config)
