name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Commitizen
        run: pip install commitizen
      - name: Check commit messages
        if: github.event_name == 'push'
        run: cz check --rev-range HEAD
      - name: Check PR commit messages
        if: github.event_name == 'pull_request'
        run: cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
