name: Run Pytest
on:
  push:
    branches: 'main'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[test]
          python3 -m pip install pytest
      - name: Create Registries
        run: |
          export GEOIPS_REBUILD_REGISTRIES=0
          export GEOIPS_PACKAGES_DIR=/
          geoips config create-reg -n runcourier.dev.plugin_packages
      - name: Run pytest
        run: |
          python3 -m pytest
